# Generated by Django 6.0.7 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
